# Generated by Django 6.0.7 on 2026-08-07 16:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('computing', 'Computing'), ('electronics', 'Electronics'), ('mechanical', 'Mechanical'), ('chemical', 'Chemical'), ('physics', 'Physics'), ('civil', 'Civil'), ('av', 'Audio/Visual'), ('furniture', 'Furniture'), ('safety', 'Safety Equipment'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_schedulable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'db_table': 'universities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('exam_start_date', models.DateField(blank=True, null=True)),
                ('exam_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_sessions',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status'], name='idx_session_status'), models.Index(fields=['start_date', 'end_date'], name='idx_session_dates')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('theory_hours', models.PositiveSmallIntegerField(default=0)),
                ('lab_hours', models.PositiveSmallIntegerField(default=0)),
                ('weekly_hours', models.PositiveSmallIntegerField()),
                ('course_type', models.CharField(choices=[('theory', 'Theory Only'), ('lab', 'Lab Only'), ('theory_lab', 'Theory + Lab'), ('project', 'Project'), ('thesis', 'Thesis'), ('seminar', 'Seminar')], default='theory', max_length=20)),
                ('max_students_per_section', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='scheduler.course')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='A', max_length=20)),
                ('max_students', models.PositiveSmallIntegerField(default=50)),
                ('current_enrollment', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('scheduling', 'In Scheduling'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('requires_lab', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_offerings', to='scheduler.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offerings', to='scheduler.course')),
            ],
            options={
                'db_table': 'course_offerings',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('repairing', 'Under Repair'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_by_ga', models.BooleanField(default=False)),
                ('fitness_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_schedules', to='scheduler.academicsession')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='scheduler.courseoffering')),
            ],
            options={
                'db_table': 'course_schedules',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('coordinator', 'Scheduling Coordinator'), ('dept_head', 'Department Head'), ('faculty', 'Faculty Member'), ('auditor', 'Auditor'), ('lab_engineer', 'Lab Engineer')], default='faculty', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='scheduler.department')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departments', to='scheduler.faculty'),
        ),
        migrations.CreateModel(
            name='FairnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('per_student_hours', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('fairness_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fairness_records', to='scheduler.department')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fairness_records', to='scheduler.courseschedule')),
            ],
            options={
                'db_table': 'fairness_records',
            },
        ),
        migrations.CreateModel(
            name='GARun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(choices=[('nsga2', 'NSGA-II'), ('nsga3', 'NSGA-III'), ('moead', 'MOEA/D'), ('spea2', 'SPEA2'), ('ga_simple', 'Simple GA'), ('ga_adaptive', 'Adaptive GA'), ('repair_ga', 'Repair GA')], default='nsga2', max_length=20)),
                ('schedule_type', models.CharField(choices=[('course', 'Course Scheduling'), ('lab', 'Lab Scheduling'), ('exam', 'Exam Scheduling'), ('invigilation', 'Invigilation Scheduling'), ('combined', 'Combined Scheduling')], default='course', max_length=20)),
                ('population_size', models.PositiveIntegerField(default=100)),
                ('generations', models.PositiveIntegerField(default=500)),
                ('mutation_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('crossover_rate', models.DecimalField(decimal_places=4, default=0.8, max_digits=5)),
                ('elitism_count', models.PositiveIntegerField(default=5)),
                ('tournament_size', models.PositiveSmallIntegerField(default=3)),
                ('convergence_threshold', models.DecimalField(decimal_places=4, default=0.001, max_digits=5)),
                ('fitness_best', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fitness_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fitness_worst', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fairness_score_before', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fairness_score_after', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('jain_index', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_peak_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('convergence_generation', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('log_output', models.TextField(blank=True)),
                ('parameters_json', models.JSONField(blank=True, default=dict, help_text='Additional GA parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ga_runs', to='scheduler.academicsession')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_runs', to='scheduler.department')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ga_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='ga_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='scheduler.garun'),
        ),
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_batch', models.CharField(blank=True, help_text='Lab batch if groups are split', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('repairing', 'Under Repair'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_by_ga', models.BooleanField(default=False)),
                ('fitness_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_schedules', to='scheduler.academicsession')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_schedules', to='scheduler.courseoffering')),
                ('ga_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_schedules', to='scheduler.garun')),
            ],
            options={
                'db_table': 'lab_schedules',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField()),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('REPAIR', 'Repair'), ('PRIORITY_RESOLUTION', 'Priority Resolution'), ('FAIRNESS_CHECK', 'Fairness Check'), ('GENERATION', 'Schedule Generation'), ('ROLLBACK', 'Rollback'), ('GA_RUN', 'GA Execution')], max_length=30)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.PositiveIntegerField()),
                ('data_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('current_hash', models.CharField(max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ga_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='scheduler.garun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger',
                'ordering': ['block_number'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('degree_type', models.CharField(choices=[('bs', 'Bachelor of Science'), ('ms', 'Master of Science'), ('phd', 'Doctor of Philosophy'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='bs', max_length=20)),
                ('duration_semesters', models.PositiveSmallIntegerField(default=8)),
                ('total_credit_hours', models.PositiveSmallIntegerField(default=130)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programs', to='scheduler.department')),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='scheduler.program'),
        ),
        migrations.CreateModel(
            name='RepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disruption_type', models.CharField(choices=[('teacher_absence', 'Teacher Absence'), ('room_unavailable', 'Room Unavailable'), ('time_conflict', 'Time Conflict'), ('fairness_violation', 'Fairness Violation'), ('priority_conflict', 'Priority Conflict'), ('manual_override', 'Manual Override'), ('lab_equipment_failure', 'Lab Equipment Failure'), ('student_group_merge', 'Student Group Merge'), ('ga_failure', 'GA Failure')], max_length=30)),
                ('stability_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fairness_before', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('fairness_after', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('repair_time_ms', models.PositiveIntegerField(default=0)),
                ('action_taken', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('partial', 'Partial Success')], default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ga_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs', to='scheduler.garun')),
                ('original_lab_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repair_original_lab', to='scheduler.labschedule')),
                ('original_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repair_original', to='scheduler.courseschedule')),
                ('repaired_lab_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_result_lab', to='scheduler.labschedule')),
                ('repaired_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_result', to='scheduler.courseschedule')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repair_history',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('exam_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='scheduler.department')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='scheduler.roomtype')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='labschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_schedules', to='scheduler.room'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('final', 'Final'), ('quiz', 'Quiz'), ('lab_exam', 'Lab Exam'), ('presentation', 'Presentation'), ('viva', 'Viva Voce')], default='mid_term', max_length=20)),
                ('exam_date', models.DateField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('max_marks', models.PositiveSmallIntegerField(default=100)),
                ('passing_marks', models.PositiveSmallIntegerField(default=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('repairing', 'Under Repair'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_by_ga', models.BooleanField(default=False)),
                ('fitness_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='scheduler.academicsession')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='scheduler.courseoffering')),
                ('ga_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='scheduler.garun')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='scheduler.room')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_schedules', to='scheduler.room'),
        ),
        migrations.CreateModel(
            name='RoomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_installations', to='scheduler.equipment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_equipment', to='scheduler.room')),
            ],
            options={
                'db_table': 'room_equipment',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lab_room_type_required',
            field=models.ForeignKey(blank=True, help_text='Required room type for lab sessions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_courses', to='scheduler.roomtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_type_required',
            field=models.ForeignKey(help_text='Preferred room type for theory classes', on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='scheduler.roomtype'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='scheduler.program')),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['program', 'semester_number'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(help_text='Which semester of the program this course belongs to', on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='scheduler.semester'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='scheduler.academicsession')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='scheduler.program')),
                ('current_semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='scheduler.semester')),
            ],
            options={
                'db_table': 'batches',
                'ordering': ['-batch_year'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
                ('size', models.PositiveIntegerField()),
                ('representative_name', models.CharField(blank=True, max_length=100)),
                ('representative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_groups', to='scheduler.batch')),
            ],
            options={
                'db_table': 'student_groups',
                'ordering': ['batch', 'section_name'],
            },
        ),
        migrations.AddField(
            model_name='labschedule',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_schedules', to='scheduler.studentgroup'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_schedules', to='scheduler.studentgroup'),
        ),
        migrations.CreateModel(
            name='CourseOfferingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='True if this is the home section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='scheduler.courseoffering')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='scheduler.studentgroup')),
            ],
            options={
                'db_table': 'course_offering_groups',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('lab_engineer', 'Lab Engineer'), ('visiting_faculty', 'Visiting Faculty'), ('research_associate', 'Research Associate')], default='lecturer', max_length=30)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('visiting', 'Visiting')], default='full_time', max_length=20)),
                ('max_teaching_hours', models.PositiveSmallIntegerField(default=18)),
                ('max_lab_hours', models.PositiveSmallIntegerField(default=6)),
                ('max_invigilation_hours', models.PositiveSmallIntegerField(default=20)),
                ('max_consecutive_invigilation', models.PositiveSmallIntegerField(default=2)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teachers', to='scheduler.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.AddField(
            model_name='labschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_schedules', to='scheduler.teacher'),
        ),
        migrations.CreateModel(
            name='InvigilationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_per_week', models.PositiveSmallIntegerField(default=5)),
                ('max_per_day', models.PositiveSmallIntegerField(default=2)),
                ('no_consecutive_days', models.BooleanField(default=False)),
                ('preferred_weekdays', models.JSONField(blank=True, default=list, help_text='[1,2,3,4,5] for Mon-Fri')),
                ('unavailable_dates', models.JSONField(blank=True, default=list, help_text="['2026-12-15', '2026-12-16']")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_preferences', to='scheduler.academicsession')),
                ('preferred_rooms', models.ManyToManyField(blank=True, related_name='invigilator_preferences', to='scheduler.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_preferences', to='scheduler.teacher')),
            ],
            options={
                'db_table': 'invigilation_preferences',
            },
        ),
        migrations.CreateModel(
            name='InvigilationDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_invigilator', 'Head Invigilator'), ('invigilator', 'Invigilator'), ('relief', 'Relief'), ('supervisor', 'Supervisor'), ('coordinator', 'Exam Coordinator')], default='invigilator', max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('replaced', 'Replaced'), ('declined', 'Declined')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invigilation_duties', to='scheduler.exam')),
                ('ga_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilation_duties', to='scheduler.garun')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invigilation_duties', to='scheduler.teacher')),
            ],
            options={
                'db_table': 'invigilation_duties',
            },
        ),
        migrations.CreateModel(
            name='GlobalFairnessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lab_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exam_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('invigilation_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('combined_workload', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('jain_index', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fairness_snapshots', to='scheduler.academicsession')),
                ('course_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairness_snapshots', to='scheduler.courseschedule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fairness_snapshots', to='scheduler.teacher')),
            ],
            options={
                'db_table': 'global_fairness_snapshots',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties_dean', to='scheduler.teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_head', to='scheduler.teacher'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_schedules', to='scheduler.teacher'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='lab_teacher',
            field=models.ForeignKey(blank=True, help_text='Lab instructor (if different from primary)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_offerings', to='scheduler.teacher'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='primary_teacher',
            field=models.ForeignKey(help_text='Main instructor for theory', on_delete=django.db.models.deletion.RESTRICT, related_name='primary_offerings', to='scheduler.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lab_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exam_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('invigilation_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('combined_workload', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overload_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teacher_workloads', to='scheduler.academicsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='scheduler.department')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='workload', to='scheduler.teacher')),
            ],
            options={
                'db_table': 'teacher_workload',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_friday', models.BooleanField(default=False, help_text='True if this slot is on Friday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['day_of_week'], name='idx_slot_day'), models.Index(fields=['slot_type'], name='idx_slot_type'), models.Index(fields=['is_friday'], name='idx_slot_friday')],
                'constraints': [models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time'), name='uq_time_slot')],
            },
        ),
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('is_available', models.BooleanField(default=True)),
                ('preference_level', models.PositiveSmallIntegerField(default=5, help_text='1=Strongly Avoid, 10=Strongly Prefer')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preferences', to='scheduler.academicsession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='scheduler.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preferences', to='scheduler.timeslot')),
            ],
            options={
                'db_table': 'teacher_preferences',
            },
        ),
        migrations.AddField(
            model_name='labschedule',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_schedules', to='scheduler.timeslot'),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='scheduler.timeslot'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_schedules', to='scheduler.timeslot'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='faculties', to='scheduler.university'),
        ),
        migrations.CreateModel(
            name='ConstraintCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_name', models.CharField(max_length=100)),
                ('constraint_type', models.CharField(choices=[('hard', 'Hard Constraint'), ('soft', 'Soft Constraint'), ('priority', 'Priority Rule'), ('preference', 'Preference Rule')], default='hard', max_length=20)),
                ('target_table', models.CharField(choices=[('course_schedules', 'Course Schedule'), ('lab_schedules', 'Lab Schedule'), ('exams', 'Exam'), ('invigilation_duties', 'Invigilation Duty'), ('teachers', 'Teacher'), ('rooms', 'Room'), ('time_slots', 'Time Slot')], max_length=30)),
                ('target_column', models.CharField(blank=True, max_length=50, null=True)),
                ('rule_definition', models.JSONField(help_text='JSON rule for GA validation engine')),
                ('error_message', models.CharField(default='Constraint violation detected', max_length=255)),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, help_text='Penalty weight for soft constraints', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applies_to_session', models.ForeignKey(blank=True, help_text='NULL = applies to all sessions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduler.academicsession')),
            ],
            options={
                'db_table': 'constraints_catalog',
                'indexes': [models.Index(fields=['constraint_type'], name='idx_constraint_type'), models.Index(fields=['target_table'], name='idx_constraint_table'), models.Index(fields=['is_active'], name='idx_constraint_active'), models.Index(fields=['priority'], name='idx_constraint_priority')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='idx_users_dept'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_users_active'),
        ),
        migrations.AddIndex(
            model_name='fairnessrecord',
            index=models.Index(fields=['schedule'], name='idx_fair_sched'),
        ),
        migrations.AddIndex(
            model_name='fairnessrecord',
            index=models.Index(fields=['department'], name='idx_fair_dept'),
        ),
        migrations.AddIndex(
            model_name='garun',
            index=models.Index(fields=['algorithm'], name='idx_ga_algorithm'),
        ),
        migrations.AddIndex(
            model_name='garun',
            index=models.Index(fields=['schedule_type'], name='idx_ga_schedule_type'),
        ),
        migrations.AddIndex(
            model_name='garun',
            index=models.Index(fields=['academic_session'], name='idx_ga_session'),
        ),
        migrations.AddIndex(
            model_name='garun',
            index=models.Index(fields=['department'], name='idx_ga_dept'),
        ),
        migrations.AddIndex(
            model_name='garun',
            index=models.Index(fields=['status'], name='idx_ga_status'),
        ),
        migrations.AddIndex(
            model_name='garun',
            index=models.Index(fields=['created_at'], name='idx_ga_created'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['block_number'], name='idx_ledger_block'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['action_type'], name='idx_ledger_action'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['table_name'], name='idx_ledger_table'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['timestamp'], name='idx_ledger_timestamp'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['user'], name='idx_ledger_user'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['ga_run'], name='idx_ledger_ga_run'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['department'], name='idx_program_dept'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['degree_type'], name='idx_program_degree'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='uq_program_dept_code'),
        ),
        migrations.AddIndex(
            model_name='repairhistory',
            index=models.Index(fields=['original_schedule'], name='idx_repair_orig_sched'),
        ),
        migrations.AddIndex(
            model_name='repairhistory',
            index=models.Index(fields=['disruption_type'], name='idx_repair_type'),
        ),
        migrations.AddIndex(
            model_name='repairhistory',
            index=models.Index(fields=['status'], name='idx_repair_status'),
        ),
        migrations.AddIndex(
            model_name='repairhistory',
            index=models.Index(fields=['ga_run'], name='idx_repair_ga_run'),
        ),
        migrations.AddIndex(
            model_name='repairhistory',
            index=models.Index(fields=['created_at'], name='idx_repair_created'),
        ),
        migrations.AddConstraint(
            model_name='roomequipment',
            constraint=models.UniqueConstraint(fields=('room', 'equipment'), name='uq_room_equipment'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='idx_room_type'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['capacity'], name='idx_room_capacity'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['department'], name='idx_room_dept'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building'], name='idx_room_building'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='idx_room_active'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('program', 'semester_number'), name='uq_semester_program_num'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['program'], name='idx_course_program'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester'], name='idx_course_semester'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='idx_course_type'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='idx_course_active'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['program'], name='idx_batch_program'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['intake_session'], name='idx_batch_session'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['current_semester'], name='idx_batch_semester'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('program', 'batch_year'), name='uq_batch_program_year'),
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['batch'], name='idx_group_batch'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('batch', 'section_name'), name='uq_group_batch_section'),
        ),
        migrations.AddIndex(
            model_name='courseofferinggroup',
            index=models.Index(fields=['course_offering'], name='idx_offergroup_offering'),
        ),
        migrations.AddIndex(
            model_name='courseofferinggroup',
            index=models.Index(fields=['student_group'], name='idx_offergroup_group'),
        ),
        migrations.AddConstraint(
            model_name='courseofferinggroup',
            constraint=models.UniqueConstraint(fields=('course_offering', 'student_group'), name='uq_offering_group'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='idx_teacher_dept'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['designation'], name='idx_teacher_designation'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employment_type'], name='idx_teacher_emp_type'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active'], name='idx_teacher_active'),
        ),
        migrations.AddIndex(
            model_name='invigilationpreference',
            index=models.Index(fields=['teacher', 'academic_session'], name='idx_invig_pref_teacher_session'),
        ),
        migrations.AddConstraint(
            model_name='invigilationpreference',
            constraint=models.UniqueConstraint(fields=('teacher', 'academic_session'), name='uq_invig_pref_teacher_session'),
        ),
        migrations.AddIndex(
            model_name='invigilationduty',
            index=models.Index(fields=['exam'], name='idx_invig_exam'),
        ),
        migrations.AddIndex(
            model_name='invigilationduty',
            index=models.Index(fields=['teacher'], name='idx_invig_teacher'),
        ),
        migrations.AddIndex(
            model_name='invigilationduty',
            index=models.Index(fields=['role'], name='idx_invig_role'),
        ),
        migrations.AddIndex(
            model_name='invigilationduty',
            index=models.Index(fields=['status'], name='idx_invig_status'),
        ),
        migrations.AddIndex(
            model_name='invigilationduty',
            index=models.Index(fields=['ga_run'], name='idx_invig_ga_run'),
        ),
        migrations.AddConstraint(
            model_name='invigilationduty',
            constraint=models.UniqueConstraint(fields=('exam', 'teacher'), name='uq_invig_exam_teacher'),
        ),
        migrations.AddIndex(
            model_name='globalfairnesssnapshot',
            index=models.Index(fields=['teacher'], name='idx_gfs_teacher'),
        ),
        migrations.AddIndex(
            model_name='globalfairnesssnapshot',
            index=models.Index(fields=['academic_session'], name='idx_gfs_session'),
        ),
        migrations.AddIndex(
            model_name='globalfairnesssnapshot',
            index=models.Index(fields=['snapshot_at'], name='idx_gfs_snapshot_at'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['faculty'], name='idx_dept_faculty'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course'], name='idx_offering_course'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['academic_session'], name='idx_offering_session'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['primary_teacher'], name='idx_offering_teacher'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['status'], name='idx_offering_status'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'academic_session', 'section_name'), name='uq_offering_course_session_section'),
        ),
        migrations.AddIndex(
            model_name='teacherworkload',
            index=models.Index(fields=['teacher'], name='idx_workload_teacher'),
        ),
        migrations.AddIndex(
            model_name='teacherworkload',
            index=models.Index(fields=['department'], name='idx_workload_dept'),
        ),
        migrations.AddIndex(
            model_name='teacherworkload',
            index=models.Index(fields=['academic_session'], name='idx_workload_session'),
        ),
        migrations.AddConstraint(
            model_name='teacherworkload',
            constraint=models.UniqueConstraint(fields=('teacher', 'academic_session'), name='uq_workload_teacher_session'),
        ),
        migrations.AddIndex(
            model_name='teacherpreference',
            index=models.Index(fields=['teacher', 'academic_session'], name='idx_pref_teacher_session'),
        ),
        migrations.AddIndex(
            model_name='teacherpreference',
            index=models.Index(fields=['day_of_week'], name='idx_pref_day'),
        ),
        migrations.AddIndex(
            model_name='teacherpreference',
            index=models.Index(fields=['is_available'], name='idx_pref_available'),
        ),
        migrations.AddIndex(
            model_name='teacherpreference',
            index=models.Index(fields=['preference_level'], name='idx_pref_level'),
        ),
        migrations.AddConstraint(
            model_name='teacherpreference',
            constraint=models.UniqueConstraint(fields=('teacher', 'academic_session', 'time_slot'), name='uq_teacher_pref_session_slot'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['course_offering'], name='idx_lsched_offering'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['teacher'], name='idx_lsched_teacher'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['room'], name='idx_lsched_room'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['time_slot'], name='idx_lsched_slot'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['academic_session'], name='idx_lsched_session'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['status'], name='idx_lsched_status'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['ga_run'], name='idx_lsched_ga_run'),
        ),
        migrations.AddConstraint(
            model_name='labschedule',
            constraint=models.UniqueConstraint(fields=('room', 'time_slot', 'academic_session'), name='uq_lsched_room_time_session'),
        ),
        migrations.AddConstraint(
            model_name='labschedule',
            constraint=models.UniqueConstraint(fields=('teacher', 'time_slot', 'academic_session'), name='uq_lsched_teacher_time_session'),
        ),
        migrations.AddConstraint(
            model_name='labschedule',
            constraint=models.UniqueConstraint(fields=('student_group', 'time_slot', 'academic_session'), name='uq_lsched_group_time_session'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course_offering'], name='idx_exam_offering'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type'], name='idx_exam_type'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['room'], name='idx_exam_room'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_date'], name='idx_exam_date'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_session'], name='idx_exam_session'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='idx_exam_status'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['ga_run'], name='idx_exam_ga_run'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('room', 'exam_date', 'time_slot'), name='uq_exam_room_date_slot'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['course_offering'], name='idx_csched_offering'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['teacher'], name='idx_csched_teacher'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['room'], name='idx_csched_room'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['time_slot'], name='idx_csched_slot'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['academic_session'], name='idx_csched_session'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['status'], name='idx_csched_status'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['ga_run'], name='idx_csched_ga_run'),
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.UniqueConstraint(fields=('room', 'time_slot', 'academic_session'), name='uq_csched_room_time_session', violation_error_message='Room is already booked at this time.'),
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.UniqueConstraint(fields=('teacher', 'time_slot', 'academic_session'), name='uq_csched_teacher_time_session', violation_error_message='Teacher is already assigned at this time.'),
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.UniqueConstraint(fields=('student_group', 'time_slot', 'academic_session'), name='uq_csched_group_time_session', violation_error_message='Student group already has a class at this time.'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('university', 'code'), name='uq_faculty_univ_code'),
        ),
    ]
