# Generated by Django 6.0.7 on 2026-08-08 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('semester_start', 'Semester Start'), ('semester_end', 'Semester End'), ('classes_start', 'Classes Start'), ('classes_end', 'Classes End'), ('exam_week_start', 'Exam Week Start'), ('exam_week_end', 'Exam Week End'), ('registration_week_start', 'Registration Week Start'), ('registration_week_end', 'Registration Week End'), ('add_drop_start', 'Add/Drop Start'), ('add_drop_end', 'Add/Drop End'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('custom', 'Custom Event')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_blocking', models.BooleanField(default=True, help_text='If True, GA will not schedule during this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_calendar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConstraintViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('fitness_penalty', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('repair_iteration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'constraint_violations',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('holiday_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='True if this holiday repeats annually')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved'), ('holiday', 'Holiday'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room_availability',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('class', 'Class'), ('lab', 'Lab')], default='class', max_length=10)),
                ('lab_batch', models.CharField(blank=True, help_text='Lab batch if groups are split', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('repairing', 'Under Repair'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_by_ga', models.BooleanField(default=False)),
                ('fitness_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='StudentConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('exam_exam', 'Exam-Exam'), ('class_class', 'Class-Class'), ('exam_class', 'Exam-Class'), ('lab_lab', 'Lab-Lab'), ('class_lab', 'Class-Lab')], max_length=20)),
                ('conflict_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_conflicts',
            },
        ),
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teacher_leaves',
            },
        ),
        migrations.RemoveIndex(
            model_name='courseschedule',
            name='idx_csched_offering',
        ),
        migrations.RemoveIndex(
            model_name='courseschedule',
            name='idx_csched_teacher',
        ),
        migrations.RemoveIndex(
            model_name='courseschedule',
            name='idx_csched_room',
        ),
        migrations.RemoveIndex(
            model_name='courseschedule',
            name='idx_csched_slot',
        ),
        migrations.RemoveIndex(
            model_name='courseschedule',
            name='idx_csched_session',
        ),
        migrations.RemoveIndex(
            model_name='courseschedule',
            name='idx_csched_status',
        ),
        migrations.RemoveIndex(
            model_name='courseschedule',
            name='idx_csched_ga_run',
        ),
        migrations.RemoveConstraint(
            model_name='courseschedule',
            name='uq_csched_room_time_session',
        ),
        migrations.RemoveConstraint(
            model_name='courseschedule',
            name='uq_csched_teacher_time_session',
        ),
        migrations.RemoveConstraint(
            model_name='courseschedule',
            name='uq_csched_group_time_session',
        ),
        migrations.RemoveField(
            model_name='globalfairnesssnapshot',
            name='course_schedule',
        ),
        migrations.RemoveIndex(
            model_name='labschedule',
            name='idx_lsched_offering',
        ),
        migrations.RemoveIndex(
            model_name='labschedule',
            name='idx_lsched_teacher',
        ),
        migrations.RemoveIndex(
            model_name='labschedule',
            name='idx_lsched_room',
        ),
        migrations.RemoveIndex(
            model_name='labschedule',
            name='idx_lsched_slot',
        ),
        migrations.RemoveIndex(
            model_name='labschedule',
            name='idx_lsched_session',
        ),
        migrations.RemoveIndex(
            model_name='labschedule',
            name='idx_lsched_status',
        ),
        migrations.RemoveIndex(
            model_name='labschedule',
            name='idx_lsched_ga_run',
        ),
        migrations.RemoveConstraint(
            model_name='labschedule',
            name='uq_lsched_room_time_session',
        ),
        migrations.RemoveConstraint(
            model_name='labschedule',
            name='uq_lsched_teacher_time_session',
        ),
        migrations.RemoveConstraint(
            model_name='labschedule',
            name='uq_lsched_group_time_session',
        ),
        migrations.RemoveField(
            model_name='repairhistory',
            name='original_lab_schedule',
        ),
        migrations.RemoveField(
            model_name='repairhistory',
            name='repaired_lab_schedule',
        ),
        migrations.RemoveConstraint(
            model_name='roomequipment',
            name='uq_room_equipment',
        ),
        migrations.AlterField(
            model_name='constraintcatalog',
            name='target_table',
            field=models.CharField(choices=[('schedules', 'Schedule'), ('exams', 'Exam'), ('invigilation_duties', 'Invigilation Duty'), ('teachers', 'Teacher'), ('rooms', 'Room'), ('time_slots', 'Time Slot')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invigilationpreference',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list, help_text="['2026-12-15', '2022026-12-16']"),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='scheduler.academicsession'),
        ),
        migrations.AddField(
            model_name='building',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buildings', to='scheduler.university'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='scheduler.building'),
        ),
        migrations.AddField(
            model_name='constraintviolation',
            name='constraint_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='scheduler.constraintcatalog'),
        ),
        migrations.AddField(
            model_name='constraintviolation',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_violations', to='scheduler.exam'),
        ),
        migrations.AddField(
            model_name='constraintviolation',
            name='ga_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constraint_violations', to='scheduler.garun'),
        ),
        migrations.AddField(
            model_name='constraintviolation',
            name='invigilation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_violations', to='scheduler.invigilationduty'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='scheduler.academicsession'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_availability', to='scheduler.academicsession'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_availability_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='scheduler.room'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_availability', to='scheduler.timeslot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='scheduler.academicsession'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='scheduler.courseoffering'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ga_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduler.garun'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='scheduler.room'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='scheduler.studentgroup'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='scheduler.teacher'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='scheduler.timeslot'),
        ),
        migrations.AddField(
            model_name='constraintviolation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_violations', to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='globalfairnesssnapshot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairness_snapshots', to='scheduler.schedule'),
        ),
        migrations.AlterField(
            model_name='fairnessrecord',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fairness_records', to='scheduler.schedule'),
        ),
        migrations.AlterField(
            model_name='repairhistory',
            name='original_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repair_original', to='scheduler.schedule'),
        ),
        migrations.AlterField(
            model_name='repairhistory',
            name='repaired_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_result', to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='studentconflict',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_conflicts', to='scheduler.academicsession'),
        ),
        migrations.AddField(
            model_name='studentconflict',
            name='first_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_exam_conflicts', to='scheduler.exam'),
        ),
        migrations.AddField(
            model_name='studentconflict',
            name='first_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_conflicts', to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='studentconflict',
            name='second_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_exam_conflicts', to='scheduler.exam'),
        ),
        migrations.AddField(
            model_name='studentconflict',
            name='second_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_conflicts', to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='studentconflict',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='scheduler.studentgroup'),
        ),
        migrations.AddField(
            model_name='studentconflict',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_conflicts', to='scheduler.timeslot'),
        ),
        migrations.AddField(
            model_name='teacherleave',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to='scheduler.academicsession'),
        ),
        migrations.AddField(
            model_name='teacherleave',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='scheduler.teacher'),
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='ga_run',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='student_group',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='labschedule',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='labschedule',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='labschedule',
            name='ga_run',
        ),
        migrations.RemoveField(
            model_name='labschedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='labschedule',
            name='student_group',
        ),
        migrations.RemoveField(
            model_name='labschedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='labschedule',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='roomequipment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='roomequipment',
            name='room',
        ),
        migrations.AddIndex(
            model_name='academiccalendar',
            index=models.Index(fields=['academic_session', 'event_type'], name='idx_cal_session_event'),
        ),
        migrations.AddIndex(
            model_name='academiccalendar',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_cal_dates'),
        ),
        migrations.AddIndex(
            model_name='academiccalendar',
            index=models.Index(fields=['is_blocking'], name='idx_cal_blocking'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['holiday_date'], name='idx_holiday_date'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['is_recurring'], name='idx_holiday_recurring'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('holiday_date', 'academic_session'), name='uq_holiday_date_session'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['room', 'date'], name='idx_avail_room_date'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['status'], name='idx_avail_status'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['academic_session'], name='idx_avail_session'),
        ),
        migrations.AddConstraint(
            model_name='roomavailability',
            constraint=models.UniqueConstraint(fields=('room', 'date', 'time_slot'), name='uq_room_availability'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type'], name='idx_sched_type'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['course_offering'], name='idx_sched_offering'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['teacher'], name='idx_sched_teacher'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['room'], name='idx_sched_room'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['time_slot'], name='idx_sched_slot'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['academic_session'], name='idx_sched_session'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='idx_sched_status'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['ga_run'], name='idx_sched_ga_run'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('room', 'time_slot', 'academic_session'), name='uq_sched_room_time_session', violation_error_message='Room is already booked at this time.'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('teacher', 'time_slot', 'academic_session'), name='uq_sched_teacher_time_session', violation_error_message='Teacher is already assigned at this time.'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('student_group', 'time_slot', 'academic_session'), name='uq_sched_group_time_session', violation_error_message='Student group already has a class at this time.'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['schedule', 'resolved'], name='idx_cv_sched_resolved'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['exam', 'resolved'], name='idx_cv_exam_resolved'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['constraint_catalog'], name='idx_cv_constraint'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['severity'], name='idx_cv_severity'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['ga_run'], name='idx_cv_ga_run'),
        ),
        migrations.AddIndex(
            model_name='constraintviolation',
            index=models.Index(fields=['repair_iteration'], name='idx_cv_repair_iter'),
        ),
        migrations.AddIndex(
            model_name='studentconflict',
            index=models.Index(fields=['student_group', 'academic_session'], name='idx_conflict_group_session'),
        ),
        migrations.AddIndex(
            model_name='studentconflict',
            index=models.Index(fields=['conflict_date'], name='idx_conflict_date'),
        ),
        migrations.AddIndex(
            model_name='studentconflict',
            index=models.Index(fields=['is_resolved'], name='idx_conflict_resolved'),
        ),
        migrations.AddIndex(
            model_name='studentconflict',
            index=models.Index(fields=['conflict_type'], name='idx_conflict_type'),
        ),
        migrations.AddIndex(
            model_name='teacherleave',
            index=models.Index(fields=['teacher', 'start_date', 'end_date'], name='idx_leave_teacher_dates'),
        ),
        migrations.AddIndex(
            model_name='teacherleave',
            index=models.Index(fields=['is_approved'], name='idx_leave_approved'),
        ),
        migrations.AddIndex(
            model_name='teacherleave',
            index=models.Index(fields=['academic_session'], name='idx_leave_session'),
        ),
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
        migrations.DeleteModel(
            name='LabSchedule',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='RoomEquipment',
        ),
    ]
